version: '3.8'
services:
  videomicro:
    container_name: videomicroapp
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    volumes:
      - storage:/var/storage
    restart: unless-stopped
volumes:
  storage:
